# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_mix_prior_derivative <- function(b, t1, t2, p) {
    .Call(`_multinomialLogitMix_log_mix_prior_derivative`, b, t1, t2, p)
}

log_prior_mix <- function(b, t1, t2, p) {
    .Call(`_multinomialLogitMix_log_prior_mix`, b, t1, t2, p)
}

mala_proposal_cpp <- function(y, X, b, z, tau, pr, nu2) {
    .Call(`_multinomialLogitMix_mala_proposal_cpp`, y, X, b, z, tau, pr, nu2)
}

